### ISSUE TITLE
Figure out Travis CI failures

### ISSUE THREAD

**Issue by mbland** [18F/go_script#16]
Travis has started throwing errors for `./go build`:

https://travis-ci.org/18F/web-design-standards/builds/106562512
https://travis-ci.org/18F/web-design-standards/builds/106737058#L247

```
$ bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
$ ./go build
/home/travis/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'bundler' (>= 0) among 45 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/home/travis/build/18F/web-design-standards/vendor/bundle/ruby/2.2.0', execute `gem env` for more information
    from /home/travis/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
    from /home/travis/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
    from /home/travis/.rvm/gems/ruby-2.2.3/bin/bundle:22:in `<main>'
    from /home/travis/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
    from /home/travis/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

travis-ci/travis-ci#4536 references this problem, which I think has to do with the `--path` argument and `bundler` itself not being in the `BUNDLER_PATH`.

Also: https://docs.travis-ci.com/user/caching/#Bundler

cc: @juliaelman @harrisj @afeld @rogeruiz

**Comment by mbland** [comment]
The remedy per 18F/team-api.18f.gov#194 appears to be adding this to `.travis.yml`:

``` yaml
before_install:
- export GEM_HOME=$PWD/vendor/bundle/ruby/2.2.0
- gem install bundler
```

**Comment by afeld** [comment]
:unamused:

**Comment by mbland** [comment]
Actually, @jcscottiii figured out in 18F/knowledge-sharing-toolkit#3 that _this_ is actually all that's needed:

``` yaml
install:
  - echo "no install steps needed"
```

**Comment by mbland** [comment]
I understand why this is happening now (thanks to my work on [18F/knowledge-sharing-toolkit](https://github.com/18F/knowledge-sharing-toolkit), where I hit the same issue trying to Dockerize [18F/team-api-server](https://github.com/18F/team-api-server/)).

When the system invokes `bundler install --path=...`, in addition to creating the directory structure specified by `--path=...`, it also creates a `.bundle/config` file that contains:

``` yaml
---
BUNDLE_PATH: vendor/bundle
BUNDLE_DISABLE_SHARED_GEMS: '1'
```

When `./go build` runs, it calls `GoScript.build_jekyll` from [go_script/go.rb](https://github.com/18F/go_script/blob/master/lib/go_script/go.rb). That command executes `JEKYLL_BUILD_CMD`, defined as:

``` ruby
JEKYLL_BUILD_CMD = 'bundle exec jekyll build --trace'
```

So when executing the `./go` script, `require 'bundler/setup'` reads `.bundle/config` and sets the gem path accordingly. Then when `JEKYLL_BUILD_COMMAND` runs, `bundle` can't find its own implementation, since the gem path is now `vendor/bundle` and shared gems are disabled. From the bottom of this stack trace:

``` sh
team-api@e094cab62656:/usr/local/18f/team-api/team-api.18f.gov$ ./go build
Building internal version...
/usr/local/18f/rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'bundler' (>= 0.a) among 46 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/usr/local/18f/team-api/team-api.18f.gov/vendor/bundle/ruby/2.3.0', execute `gem env` for more information
        from /usr/local/18f/rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
        from /usr/local/18f/rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
        from /usr/local/18f/rbenv/versions/2.3.0/bin/bundle:22:in `<main>'
```

we can see that `/usr/local/18f/rbenv/versions/2.3.0/bin/bundle:22` invokes:

``` ruby
gem 'bundler', version
```

There are two workarounds. One, set `BUNDLE_DISABLE_SHARED_GEMS` to `false`. Two, make sure to do the `gem install bundler` bit as mentioned above (re: 18F/team-api.18f.gov#194) before invoking `./go build`.

The "real" solution, however, is to make `go_script` detect when `.bundle/config` is present and install bundler as necessary.

**Comment by mbland** [comment]
_Or_, we can remove the `bundle exec` from the `JEKYLL_BUILD_COMMAND`, since the `./go` script itself calls `require 'bundler/setup'` first thing. I'll try that.

**Comment by mbland** [comment]
Turns out #17 introduced a new issue, and not just a Travis issue, but a general Jekyll build issue. #18 is now out to resolve this issue.

Removing `bundle exec` from JEKYLL_BUILD_CMD in that pull request meant that BUNDLE_BIN_PATH and BUNDLE_GEMFILE weren't set for the Jekyll child process. Therefore, when Jekyll tried to load a gem from the :jekyll_plugins group, it couldn't find it. From https://travis-ci.org/18F/before-you-ship/builds/112281551:

```
$ ./go ci_test
/home/travis/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in
`rescue in block (2 levels) in require': There was an error while trying to
load the gem 'guides_style_18f'. (Bundler::GemRequireError)
        from
/home/travis/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in
`block (2 levels) in require'
        from
/home/travis/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in
`each'
        from
/home/travis/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in
`block in require'
        from
/home/travis/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in
`each'
        from
/home/travis/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in
`require'
        from
/home/travis/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.11.2/lib/bundler.rb:99:in
`require'
        from
/home/travis/build/18F/before-you-ship/vendor/bundle/ruby/2.2.0/gems/jekyll-3.1.2/lib/jekyll/plugin_manager.rb:34:in
`require_from_bundler'
        from
/home/travis/build/18F/before-you-ship/vendor/bundle/ruby/2.2.0/gems/jekyll-3.1.2/bin/jekyll:9:in
`<top (required)>'
        from
/home/travis/build/18F/before-you-ship/vendor/bundle/ruby/2.2.0/bin/jekyll:23:in
`load'
        from
/home/travis/build/18F/before-you-ship/vendor/bundle/ruby/2.2.0/bin/jekyll:23:in
`<main>'
```

The tests added in #17 didn't catch this because they only tried to execute the `./go` script rather than build a Jekyll site containing a plugin. The updated tests, which now build a Jekyll site with the guides_style_18f plugin, both reproduce the above error and verify its fix.
